### PR TITLE
general review

### PR DESCRIPTION
**Pull request by ngoix**

### CODE REVIEW

**Comment by ngoix** [comment]
ping @datajms @RonanGautier @floriangardin

**Comment by datajms** [comment]
examples/plot_credit_default.py  delete the line L57 :
 # data = pd.get_dummies(data, columns = ['SEX', 'EDUCATION', 'MARRIAGE'])

**Comment by datajms** [comment]
examples/plot_credit_default.py replace line L83
old_value : print(feature_names)
new_value : print("List of variables used to train models : "+str(feature_names))

**Comment by datajms** [comment]
examples/plot_credit_default.py replace line L93
old_value : # Benchmark with a Decision Tree and Random Forests
new_value : # Benchmark with a Random Forest

**Comment by datajms** [comment]
examples/plot_credit_default.py replace line L96 etc.
 old_value : This part shows the training and performance evaluation of two tree-based models. The objective remains to extract rules which targets credit defaults. This benchmark shows the performance reached with a decision tree and a random forest. 
new_value : This part shows the training and performance evaluation of a random forest model. The objective remains to extract rules which targets credit defaults.

**Comment by datajms** [comment]
examples/plot_credit_default.py replace line L109 etc.
 old_value : 'max_features': np.linspace(0.1, 0.2, 1.)
 new_value : 'max_features': np.linspace(0.1, 0.7, 7)

**Comment by datajms** [comment]
examples/plot_credit_default.py delete line L119 etc.
old_value : # print("Decision Tree selected parameters : "+str(DT.best_params_))

**Comment by datajms** [comment]
examples/plot_credit_default.py delete line L126 and L135 etc.
 old_value : fpr_DT, tpr_DT, _ = roc_curve(y_test, scoring_DT)
precision_DT, recall_DT, _ = precision_recall_curve(y_test, scoring_DT)

**Comment by RonanGautier** [comment]
- [ ] file index.rst : Application domains include fraud detection, predictive maintenance, intrusion detection, churn detection**...** 

- [ ] file Makefile : remove the last 'the' at line 56

- [ ] file skope_rules.py : 

-  remove bold style  at line 25, 29 and 32 

- standardize  the text at line 30 and 33 

- add a dash at lines 98, 99 and 100

- line 53 : font problem

**Comment by datajms** [comment]
examples/plot_credit_default.py change line L212.
old_value : generated by SkopeRulesthe (blue points) and the performance of the Random
old_value : generated by SkopeRules (the blue points) and the performance of the Random

**Pull request merged**
